### ISSUE TITLE
Advertisement include_tx_power setter typo

### ISSUE THREAD

**Issue by kellyjp** [ukBaz/python-bluezero#117]
The setter method for the include_tx_power property of the Advertisement class calls the "set" method  which doesn't exist.  It should instead call the "Set" method.

**Comment by ukBaz** [comment]
Well spotted!

Feel free to do a pull request or I'll take a look once I can get back to my development environment in a week or so

**Comment by ukBaz** [comment]
I've started to look at. Before making the simple fix I am taking a look at doing some tests first to stop such errors slipping through.

@mr499 : Have you looked at tests for advertising at all?

**Comment by ukBaz** [comment]
I've just fixed the typo and done some manual testing so I can close this issue.

My investigations into getting something automated using Travis were unsuccessful.

If anyone has ideas how we can get better test coverage on this library with automated testing then please let me know.
