### ISSUE TITLE
 Connection ":1.5" is not allowed to own the service

### ISSUE THREAD

**Issue by vbisbest** [ukBaz/python-bluezero#128]
I am trying to run fatbeacon.py and I get this error.  Ideas?

dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.5" is not allowed to own the service "ukBaz.bluezero" due to security policies in the configuration file

**Comment by ukBaz** [comment]
It sounds like you might have skipped the following step in your setup:
https://github.com/ukBaz/python-bluezero/blob/master/docs/install_bluez.rst#creating-a-bluezero-peripheral

**Comment by ukBaz** [comment]
I am going to assume this is closed as you have moved on to asking different questions. If this isn't resolved then please re-open with more information
