### ISSUE TITLE
raspberry pi dbus.exceptions.DBusException: org.freedesktop.DBus.Error.InvalidArgs: No such property 'ServicesResolved'

### ISSUE THREAD

**Issue by RaspM** [ukBaz/python-bluezero#131]
```
pi@raspberrypi:~ $ sudo python3 /home/pi/python-bluezero/microbit_button.py E4:BE:8D:F3:BB:B4
Traceback (most recent call last):
  File "/home/pi/python-bluezero/microbit_button.py", line 188, in <module>
    central(str(args.address))
  File "/home/pi/python-bluezero/microbit_button.py", line 130, in central
    ubit.connect()
  File "/home/pi/python-bluezero/microbit_button.py", line 63, in connect
    'ServicesResolved'):
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.InvalidArgs: No such property 'ServicesResolved'
```

my raspberry pi and micro:bit is paired successfully   throughout, so i am wondering what is the issue .

```
[bluetooth]# paired-devices
Device E4:BE:8D:F3:BB:B4 BBC micro:bit
```
 
i have also instaleed bluezero and i ran it on the terminal but to no avail.
any help extended is appreciated. Thank you.

I m currently using blueZ 5.4.3 and am using raspberry Pi3

**Comment by ukBaz** [comment]
Thanks for looking at Bluezero.

I am going to need some more information before I can give you any sensible suggestions.

Can you run `bluetoothctl` on the command line. Once using `bluetoothctl` can you run the following commands:
`version`
`show`
`connect E4:BE:8D:F3:BB:B4`

And post the output from that to this issue.

Thanks,
Barry

**Comment by RaspM** [comment]
![image](https://user-images.githubusercontent.com/29479515/27266342-0381b866-54d3-11e7-82af-f2488a83f8ac.png)
![image](https://user-images.githubusercontent.com/29479515/27266365-40dad8dc-54d3-11e7-891b-272a451abe67.png)
sorry foe the late reply.

**Comment by ukBaz** [comment]
Hello,

Thanks for posting the requested information.
I can see the version being reported as 5.23. 
Your original error message is correct, in that version of BlueZ bluetoothd there was no `ServicesResolved` property. 
In version 5.23 the Python API was not at production status. You will need to upgrade to BlueZ version 5.43 as there have been a number of corrections to the API to get it into production status.

I have put some instructions together on how to upgrade BlueZ at:
https://github.com/ukBaz/python-bluezero/blob/master/docs/install_bluez.rst

I am going to close this issue as it is the version that is the fix. If you have other problems then please open a new issue.

Regards,
Barry
