### ISSUE TITLE
advertisement.py exposes mainloop. Is this correct?

### ISSUE THREAD

**Issue by ukBaz** [ukBaz/python-bluezero#149]
The example given in the advertisement is as follows:

    >>> from bluezero import tools
    >>> from bluezero import advertisement
    >>> beacon = advertisement.Advertisement(1, 'broadcast')
    >>> beacon.service_UUIDs = ['FEAA']
    >>> beacon.service_data =  {'FEAA': [0x10, 0x00, 0x00, 0x63, 0x73,
    >>>                                  0x72, 0x00, 0x61, 0x62, 0x6f,
    >>>                                  0x75, 0x74]}
    >>> ad_manager = advertisement.AdvertisingManager()
    >>> ad_manager.register_advertisement(beacon, {})
    >>> tools.start_mainloop()

This means that in a 'level 10' file you would need to know about mainloops which according to Bluezero's overview documentation 'It will not make reference to DBus or event loops.'

Maybe the API should be updated so the last line of the example would be:

    >>> ad_manager.start()

and then that starts the mainloop

**Comment by jrl290** [comment]
`tools` doesn't have a `start_mainloop()` function nor does `AdvertisingManager` have a `start()` function

Please advise

**Comment by ukBaz** [comment]
Ah! yes. the `start_mainloop()` has been moved to `dbus_tools`.

This is on the 'todo' list to fix by putting a `start()` in `AdvertisingManager`

Is that enough information to get you going?

If you fix it and want to create a PR then it will be happily accepted  :-)

**Comment by jrl290** [comment]
This would be my very first python project, and I have never created a PR on github before, so I will not risk destroying this project with my inexperience.

But yes, pointing to `dbus_tools` worked fine. Thank you!

**Comment by ukBaz** [comment]
Glad it worked!

I'll leave it on my todo list  :-)

**Comment by ukBaz** [comment]
The commit 5947a2b6e31b2bccd0f24e87ac6e5487b787c419 closes this issue
