### ISSUE TITLE
add bluez build and install instructions to README or INSTALL

### ISSUE THREAD

**Issue by WayneKeenan** [ukBaz/python-bluezero#16]
One day this hopefully wont't be necessary, but for now it would be good to have a recipe on how to setup the bleeding edge bluez.

So for example, this is what I have in my notes (for Raspian Jessie) but needs tweaking (specifically, i'm not convinced I've got all the paths in the configure step covered and I can't remember why I really disabled cups, maybe just to speed up build time / remove some dependancies). 

I've added this as a suggested documentation request that really needs validation by a second pair of eyes; rather than a tried and tested pull requested of a rigorously tested recipe (although I've done it dozens of times now :) )

### Install build and install dependancies:
```
sudo apt-get install libglib2.0-dev libdbus-1-dev libical-dev libusb-1.0-0.dev libreadline-dev checkinstall
```

### Download and Configure source build
```
wget http://www.kernel.org/pub/linux/bluetooth/bluez-5.39.tar.xz
tar xf bluez-5.39.tar.xz
cd bluez-5.39

./configure \
        --libdir=/lib \
        --libexec=/lib \
        --enable-experimental \
        --disable-cups 

make -j 4
```
The -j 4 will perform a concurrent build using all 4 cores, if you have them :)

### Perform an install 
This is performed as a removable debian package as opposed  to `make install` which does a blind file copy that is hard to remove.

```
sudo systemctl stop bluetooth
sudo checkinstall
```

The `check install` step will prompt for some user input, I think I have a defaults file somewhere, but it's not too onerous todo manually as many values are automatically and sensibly defaulted (some being saved to disk)
The bonus is you get a *.deb file too. This file /shouldn't/ really be passed around, but it might work on other Pi's  :)

### Enable the experimental option when the daemon starts
```
sudo sed -i '/^ExecStart.*bluetoothd\s*$/ s/$/ --experimental/' /lib/systemd/system/bluetooth.service
```
 

### Light the blue touch paper...
```
sudo systemctl daemon-reload && sudo systemctl restart bluetooth && sudo systemctl status bluetooth
sudo hciconfig hci0 up
hciconfig
```

**Comment by WayneKeenan** [comment]
Perhaps of note in all the above is that the generated debian file satisfies the Raspian Jessie 'bluez' dependancy of the 'pi-bluetooth' package (amongst others).  But as mentioned the *.deb  /shouldn't really be passed around.  It's perhaps a very good start point of creating a proper debian package.

**Comment by ukBaz** [comment]
Initial document created and added to repository
