### ISSUE TITLE
BlueZero in action!

### ISSUE THREAD

**Issue by eliotlandrum** [ukBaz/python-bluezero#195]
This isn't a problem, just wanted to share with you what I'd been working on using BlueZero for. :-) 

https://devpost.com/software/tokenized-autonomous-vehicle-charging-with-blocklet-1ws73v

There's a video at the top. It doesn't show it, but the Roomba has a Pi inside the vacuum area and there's a Pi for the dock as well (not shown). They use Eddystone beaconing to find each other (before the Roomba dock is enabled) and establish availability. Was fun to work on and I appreciate the work done in this library.

**Comment by ukBaz** [comment]
Thanks for sharing!  Very much appreciated.

Always fun to see where the library gets used.  Good luck with the project!
