### ISSUE TITLE
Is bluezero used of window 10 

### ISSUE THREAD

**Issue by xiaolongchengithub** [ukBaz/python-bluezero#231]
Hello,Thank your help.I want to use your library for windows.I need modfy ?

**Comment by ukBaz** [comment]
Bluezero library is for Linux only. Primarily for Single Board Computers like the Raspberry Pi.

There are some libraries out there that are targeted at Windows and some that are targeted to work cross platform such as:
https://github.com/TheCellule/python-bleson

As this request is outside the scope of this library I am going to close.

**Comment by ukBaz** [comment]
If you don't mind it not being Python then Web Bluetooth has the best cross platform support
https://github.com/WebBluetoothCG/web-bluetooth/blob/master/implementation-status.md

**Comment by xiaolongchengithub** [comment]
oh,I seee. thank you
