### ISSUE TITLE
Add LICENSE to pypi tarball

### ISSUE THREAD

**Issue by ffontaine** [ukBaz/python-bluezero#277]
LICENSE is not available in pypi tarball, would it possible to add it in the next releases?

**Comment by ukBaz** [comment]
Would you do that with MANIFEST.in?
https://packaging.python.org/guides/using-manifest-in/

**Comment by ffontaine** [comment]
Yes, MANIFEST.in is implemented by other python packages such as https://github.com/Nurdok/yieldfrom/blob/master/MANIFEST.in or https://github.com/aio-libs/yarl/blob/master/MANIFEST.in

**Comment by ukBaz** [comment]
Fixed with bb57b071425475bb47fee899afd0e610363620a4
