### ISSUE TITLE
Adapter start_scan() doesn't work with Python3

### ISSUE THREAD

**Issue by mr499** [ukBaz/python-bluezero#29]
I suspect this is a common python2/3 issue because of what python3 does with dictionaries.

AttributeError: 'dbus.Dictionary' object has no attribute 'iteritems'

**Comment by ukBaz** [comment]
See #2 as that was the same issue.

changed iteritems to items. It appears I missed some :-(

**Comment by ukBaz** [comment]
fixed by 98e6b2107b04341b8ca35c259772df355b020c63
