### ISSUE TITLE
Sytem seting can find ble device,But use app cannot find device

### ISSUE THREAD

**Issue by kscorpio** [ukBaz/python-bluezero#292]
I use run demo code ble_uart.py , and use many mobiles (include android and iOS) to scan , cannot find the devices
but in mobile system setiing  - bluetooth can find this device

**Comment by ukBaz** [comment]
You are going to have to give me more information if you want me to help. If just run the example again now and it has worked with [nRF Connect App ](https://www.nordicsemi.com/Software-and-tools/Development-Tools/nRF-Connect-for-mobile)on Android

**Comment by kscorpio** [comment]
could  ble service uuid definition affect it？ and the PC as peripheral bluetooth version is 4.2

**Comment by kscorpio** [comment]
Maybe I misunderstood   knowledge of Bluetooth， I use nRF connect in iphone ，nRF can find device(ble_uart) ， but  lightblue app can not find

**Comment by ukBaz** [comment]
Changing the UUID in that way shouldn't be necessary. Sounds like LightBlue isn't living up to their claim of "With LightBlue®, you can scan, connect to and browse any nearby BLE device."

**Comment by SXKJ-luochao** [comment]
I met the same problem on my raspberry pi，can't found from the nRF Connect App (Android).

![图片](https://github.com/ukBaz/python-bluezero/assets/104339963/2eb917bf-3ed4-4d72-8d55-97e1c06dafe4)

from the bluetoothctl, can see the info below:
![QQ截图20240315100949](https://github.com/ukBaz/python-bluezero/assets/104339963/ecaeb29d-42de-4c7f-87eb-e6217b0ef421)

device: raspberry pi 3B+
system: 
![图片](https://github.com/ukBaz/python-bluezero/assets/104339963/8a6a4cc2-11d1-4872-9fe4-d9437d7d4849)

bluetoothctl版本：5.64

how can i solve this problem?  thanks

**Comment by ukBaz** [comment]
@SXKJ-luochao, It would be better if you started a new issue with this rather than adding to a closed one. Especially as I don't see this as the same issue.

Can you look at the https://bluezero.readthedocs.io/en/stable/system_setup.html#notes-for-getting-debug-information section and open a new ticket if you would still like help.
