### ISSUE TITLE
Multiple Connections not possible with latest Raspian version

### ISSUE THREAD

**Issue by jofleck** [ukBaz/python-bluezero#344]
After a normal upgrade to the latest Version of Bluez and other packages (with apt) our Raspis changed the behavior. 

Before the upgrade the Raspberry (peripheral) kept advertising when a device conntected. Multiple connections were possible. 

After the upgrade the device stops advertising after the first device connects. So multiple connections are not possible. After disconnecting the Raspi continues advertising automatically. 

Does anyone have Ideas how to archieve the goal of multiple connections again? Maybe some configs were overwritten by the upgrade

Thank you soooo much :)

**Comment by ukBaz** [comment]
I thought that was always the behaviour with BlueZ that it stopped advertising when it received a connection.  Maybe a question for the BlueZ developers: http://www.bluez.org/contact/
