### ISSUE TITLE
File transfer

### ISSUE THREAD

**Issue by mrsaleh** [ukBaz/python-bluezero#345]
Hi 
How can I send a file from peripheral to the central device.
I have a 3d scanner and I want it to send the scan file to the user device which is an android application which connected to my scanner. 
Thanks in advance

**Comment by ukBaz** [comment]
Thanks for the question. Transferring files is not something that this library looks to do. However, it is something that does have good support generally in Bluetooth. Below are a couple of links to StackExchange/StackOverflow answers that talk about this topic and should helpful to get you started.

https://raspberrypi.stackexchange.com/a/119818/121848

https://stackoverflow.com/a/68541518/7721752
