### ISSUE TITLE
set_value wait for response

### ISSUE THREAD

**Issue by p30arena** [ukBaz/python-bluezero#350]
I'm using peripheral mode and writing to the characteristic using set_value

it seems sometimes the data received at the central end is corrupted or some packets are ignored by dbus

how can I discover this and retry the transmission?

**Comment by ukBaz** [comment]
If you want to try different setup then there are a few different options that are available. 

The simplest one is to change `notify` to `indicate` which will then add a confirmation on the lower level communication.
The full list of options is in the BlueZ documentation: https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/gatt-api.txt#n263

If you are sending lots of notifications then you might want to look at using a socket connection with [AcquireNotify](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/gatt-api.txt#n145). This is beyond what Bluezero plans to support

**Comment by ukBaz** [comment]
This has been sat here a while without an update so I'm closing. If it is still an issue then please re-open with more information on how to reproduce
