### ISSUE TITLE
Installing on Raspberry Pi

### ISSUE THREAD

**Issue by AlexMaghen** [ukBaz/python-bluezero#364]
Forgive my newbee question here but I'm not sure what your preferred procedure is for installing this excellent-looking library and all of its examples globally on a Raspberry Pi. Any guidance, most appreciated!

Alex

**Comment by ukBaz** [comment]
Please take a look at the documentation at: https://bluezero.readthedocs.io/en/latest/examples.html

Which also has a link to a tutorial to help get people started quickly: https://ukbaz.github.io/howto/ubit_workshop.html

**Comment by ukBaz** [comment]
No update on this for a while so I'm going to assume this is resolved. If that is not the case, please re-open
