### ISSUE TITLE
Services Resolved Description Duplicated from Services Available

### ISSUE THREAD

**Issue by chadrockey** [ukBaz/python-bluezero#368]
https://github.com/ukBaz/python-bluezero/blob/e6b4e96342de6c66571a6660d711c018f8c6b470/bluezero/central.py#L72

Sorry for the minor issue, but the comment here is the same as the other function.  This is a boolean that indicates if the services have been resolved, not a list of the services.

**Comment by ukBaz** [comment]
Well spotted! I'll update this at when I'm looking at the other issues

**Comment by ukBaz** [comment]
Sorry, missed this on the last release. Corrected now with ea8048c92fb7a231094d9588781b7a7678961f84
