### ISSUE TITLE
Typo on characteristic write

### ISSUE THREAD

**Issue by chadrockey** [ukBaz/python-bluezero#369]
https://github.com/ukBaz/python-bluezero/blob/6f46b6cb7102831c1427f12e65b727fc6b54774a/bluezero/GATT.py#L214

This line ends up printing 'onon' because on is on the end and beginning of the multiline code.

**Comment by ukBaz** [comment]
Well spotted!  I'll update this when I'm looking at the other issues.

**Comment by ukBaz** [comment]
Fixed with 4a385a2f7df2e8f946678c8bbfebecb873b28687
