### ISSUE TITLE
Name a service and a characteristic

### ISSUE THREAD

**Issue by bolinocroustibat** [ukBaz/python-bluezero#400]
Is there a way to give a string name to a service and a characteristic using `python-bluezero`, apart from the UUIDs?
This is how services and characteristics appear in nRF Connect, as "Unknown Service" and "Unknown Characteristic".

![screen](https://github.com/ukBaz/python-bluezero/assets/4353767/6b86d823-b998-4c49-87c5-9dbdd072ce4f)

**Comment by ukBaz** [comment]
The nRF Connect app uses the published list of UUIDs to look up the names of characteristics and services. There is no way of sending the name in the Bluetooth specification.

For example, the list of characteristic UUIDs is available from:
https://bitbucket.org/bluetooth-SIG/public/src/main/assigned_numbers/uuids/characteristic_uuids.yaml

If you want to register a UUID for your services and characteristic then it will cost you money. More information available at:
https://support.bluetooth.com/hc/en-us/articles/360062030092-Requesting-Assigned-Numbers
